User.create(username: "island_hopper", email: "island_hopper@gmail.com", password: "isl123")
Destination.create(name: "Honolulu", description: "", star_ranking: '10', image: "")
Destination.create(name: "Belize", description: "",star_ranking: '8', image: "")
Destination.create(name: "Punta Cana", description: "",star_ranking: '9', image: "")
Destination.create(name: "Ibiza", description: "",star_ranking: '10', image: "")
Destination.create(name: "Puerto Rico", description: "",star_ranking: '7', image: "")

User.create(username: "trvllover", email: "trvlover@gmail.com", password: "abc123")
Destination.create(name: "Vienna", description: "", star_ranking: '10', image: "")
Destination.create(name: "Barcelona", description: "",star_ranking: '9', image: "")
Destination.create(name: "Paris", description: "",star_ranking: '9', image: "")
Destination.create(name: "London", description: "",star_ranking: '10', image: "")
Destination.create(name: "Munich", description: "",star_ranking: '8', image: "")

User.create(username: "adventure5678", email: "adventure5678@gmail.com", password: "adv586")
Destination.create(name: "Himalayan Mountains", description: "", star_ranking: '10', image: "")
Destination.create(name: "Patagonia", description: "",star_ranking: '9', image: "")
Destination.create(name: "South Africa", description: "",star_ranking: '7', image: "")
Destination.create(name: "Mt. Everest", description: "",star_ranking: '10', image: "")
Destination.create(name: "Machu Picchu", description: "",star_ranking: '9', image: "")

User.create(username: "foodielover", email: "foodielover@gmail.com", password: "foodie218")
Destination.create(name: "Montreal", description: "", star_ranking: '9', image: "")
Destination.create(name: "New Orleans", description: "",star_ranking: '8', image: "")
Destination.create(name: "Palermo", description: "",star_ranking: '10', image: "")
Destination.create(name: "Tokyo", description: "",star_ranking: '8', image: "")
Destination.create(name: "Madrid", description: "",star_ranking: '9', image: "")

User.create(username: "beachesforever", email: "beachesforever@gmail.com", password: "beachesfor983")
Destination.create(name: "South Beach", description: "", star_ranking: '8', image: "")
Destination.create(name: "Grace Bay", description: "",star_ranking: '8', image: "")
Destination.create(name: "Eagle Beach", description: "",star_ranking: '10', image: "")
Destination.create(name: "Siesta Beach", description: "",star_ranking: '8', image: "")
Destination.create(name: "Playa De La Concha", description: "",star_ranking: '9', image: "")

User.create(username: "thrillseeker", email: "thrillseeker@gmail.com", password: "thrillskr")
Destination.create(name: "Kjerag Mountain", description: "", star_ranking: '10', image: "")
Destination.create(name: "Gravity Canyon", description: "",star_ranking: '8', image: "")
Destination.create(name: "Innsbruck", description: "",star_ranking: '10', image: "")
Destination.create(name: "Rio De Janeiro", description: "",star_ranking: '7', image: "")
Destination.create(name: "Mount Hua Shan", description: "",star_ranking: '9', image: "")